In [12]:

#Some images have been excluded due to too much noise/no appparent features that can be extracted

from IPython.display import display
import pandas as pd

# Path to the CSV file
csv_path = './results.csv'

# Load the CSV file into a DataFrame
results_df = pd.read_csv(csv_path)

# Filter the DataFrame to only include rows where the 'Image File' column starts with 'epoch_15'
filtered_df = results_df[results_df['Image File'].str.startswith('epoch_15')]

# Display the filtered DataFrame
print("Filtered DataFrame:")
display(filtered_df)

# Calculate the average of each numeric column
column_averages = filtered_df.mean(numeric_only=True)

# Print the average for each column
print("\nAverages for each numeric column:")
for column, avg in column_averages.items():
    print(f"{column}: {avg}")

Filtered DataFrame:

,Semi-major Axis,Semi-minor Axis,Ellipticity,Orientation Angle,Isophotal Area,Sersic Index,Image File
3,1.755813,1.340133,0.236745,1.121417,31,1.436138,epoch_15_image_10.pt
4,1.499771,1.107257,0.261716,0.708402,22,1.293428,epoch_15_image_1001.pt
5,1.972750,1.585459,0.196321,-1.402329,47,1.742426,epoch_15_image_1002.pt
6,2.617980,1.701302,0.350147,0.353714,63,0.947929,epoch_15_image_1003.pt
7,1.690844,1.331421,0.212570,1.236556,33,1.605537,epoch_15_image_1004.pt
...,...,...,...,...,...,...,...
4614,5.105482,2.986325,0.415075,0.481275,211,0.784588,epoch_15_image_986.pt
4615,2.771508,2.235505,0.193397,-0.103195,93,1.769459,epoch_15_image_987.pt
4616,3.194469,2.581301,0.191947,1.259068,147,1.783175,epoch_15_image_991.pt
4617,2.447732,1.482015,0.394536,-0.574085,49,0.830792,epoch_15_image_995.pt
4618,2.684504,2.439787,0.091159,0.188418,151,3.791301,epoch_15_image_996.pt

Averages for each numeric column:
Semi-major Axis: 2.4841456702124307
Semi-minor Axis: 1.6990777696426345
Ellipticity: 0.2969696663070217
Orientation Angle: 0.02872454487937097
Isophotal Area: 80.38561525129982
Sersic Index: 2.1172731912428744