In [7]:
from IPython.display import display
import pandas as pd

# Path to the CSV file
csv_path = './testing_metrics.csv'

# Load the CSV file into a DataFrame
results_df = pd.read_csv(csv_path)

# Display the DataFrame
display(results_df)

# Calculate the average of each numeric column, excluding 'Sequential Index' and 'Object ID'
column_averages = results_df.drop(columns=['Sequential Index', 'Object ID']).mean(numeric_only=True)

# Print the average for each column
print("\nAverages for each numeric column (excluding 'Sequential Index' and 'Object ID'):")
for column, avg in column_averages.items():
    print(f"{column}: {avg}")

,Sequential Index,Object ID,Orientation Angle,Semi-major Axis,Semi-minor Axis,Isophotal Area,Sersic Index,Ellipticity
0,0,36407063378678903,45.31,5.245,4.475,603.0,2.306,0.147
1,1,36407187932710008,-49.18,2.356,2.050,93.0,1.573,0.130
2,2,36407187932722372,30.40,4.285,3.390,254.0,1.235,0.209
3,3,36407187932722754,53.20,11.081,5.260,1064.0,1.440,0.525
4,4,36407187932723360,20.62,9.143,2.396,386.0,0.910,0.738
...,...,...,...,...,...,...,...,...
40909,40909,74649164419438448,10.98,3.556,2.804,194.0,1.361,0.211
40910,40910,74649164419461709,2.47,3.126,3.057,202.0,1.617,0.022
40911,40911,74649164419466121,26.11,2.914,2.696,303.0,1.392,0.075
40912,40912,74649168714403940,-12.47,2.764,2.395,128.0,0.593,0.133
40913,40913,74649168714406416,-57.72,3.181,2.527,148.0,0.796,0.206

Averages for each numeric column (excluding 'Sequential Index' and 'Object ID'):
Orientation Angle: 0.2664048980788973
Semi-major Axis: 5.523995624969449
Semi-minor Axis: 3.851766510240994
Isophotal Area: 694.7817861856577
Sersic Index: 1.3575282788287626
Ellipticity: 0.23057875054993404